services:
  server:
    image: ghcr.io/htilssu/api-med-deploy
    environment:
      - PORT=8000
      - HUGGINGFACE_TOKEN=
      - MONGO_URI=mongodb://root:root@mongo
    ports:
      - "8080:8080"
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: